package org.drools.examples.helloworld

import java.util.Map
import java.util.Objects



rule "pact_add_update_back1"
    agenda-group "pact_add_update_back"
    dialect "java"
    when
        map :Map(this['type'] == 1 && this['money'] <= 200000)
    then
        map.put("res",1);
end

rule "pact_add_update_back2"
    agenda-group "pact_add_update_back"
    dialect "java"
    when
        map :Map(this['type'] == 1 && this['money'] > 200000)
    then
        map.put("res",2);
end


rule "pact_add_update_back3"
    agenda-group "pact_add_update_back"
    dialect "java"
    when
        map :Map(this['type'] == 2 && this['money'] <= 50000)
    then
        map.put("res",3);
end


rule "pact_add_update_back4"
    agenda-group "pact_add_update_back"
    dialect "java"
    when
        map :Map(this['type'] == 2 && this['money'] > 50000 && this['money'] <= 200000)
    then
        map.put("res",4);
end


rule "pact_add_update_back5"
    agenda-group "pact_add_update_back"
    dialect "java"
    when
        map :Map(this['type'] == 2 && this['money'] > 200000)
    then
        map.put("res",5);
end