/*
 * Copyright 2010 Red Hat, Inc. and/or its affiliates.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *      http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

package org.drools.examples.helloworld

import java.util.Map
import java.util.Objects
global java.util.List list



rule "request1"
    agenda-group "request"
    dialect "java"
    when
        map :Map(this['type'] == 1)
    then
        map.put("res",1);
        System.out.println("request.drl request1 invoke");
end

rule "request2"
    agenda-group "request"
    dialect "java"
    when
        map :Map(this['type'] == 2 && this['money'] <= 50000)
    then
        map.put("res",2);
        System.out.println("request.drl request2 invoke");
end


rule "request3"
    agenda-group "request"
    dialect "java"
    when
        map :Map(this['type'] == 2 && this['money'] > 50000 && this['money'] <= 1000000)
    then
        map.put("res",3);
        System.out.println("request.drl request3 invoke");
end


rule "request4"
    agenda-group "request"
    dialect "java"
    when
        map :Map(this['type'] == 2 && this['money'] > 1000000)
    then
        map.put("res",4);
        System.out.println("request.drl request4 invoke");
end
